"""club_normalized_name

Revision ID: 0e6940c4b82b
Revises: 33467da2a5f3
Create Date: 2026-10-08 15:08:04.059315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e6940c4b82b'
down_revision: Union[str, Sequence[str], None] = '33467da2a5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_club_normalized_name'), 'club', ['normalized_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_club_normalized_name'), table_name='club')
    op.drop_column('club', 'normalized_name')
    # ### end Alembic commands ###
