"""username_case_insensitive

Revision ID: 18a3fdfebc80
Revises: 97c3eb4e4963
Create Date: 2026-10-04 17:00:57.698168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a3fdfebc80'
down_revision: Union[str, Sequence[str], None] = '97c3eb4e4963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_username_lower', 'user', [sa.literal_column('lower(username)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username_lower', table_name='user')
    # ### end Alembic commands ###
