"""refresh_grace_period

Revision ID: ec67dc2ad175
Revises: 964eba968a2c
Create Date: 2026-09-30 10:49:51.046641

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "ec67dc2ad175"
down_revision: Union[str, Sequence[str], None] = "964eba968a2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_sessions",
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "refresh_sessions",
        sa.Column(
            "next_access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "refresh_sessions",
        sa.Column(
            "next_refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "refresh_sessions",
        sa.Column("next_access_expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_sessions", "next_access_expires_at")
    op.drop_column("refresh_sessions", "next_refresh_token")
    op.drop_column("refresh_sessions", "next_access_token")
    op.drop_column("refresh_sessions", "revoked_at")
    # ### end Alembic commands ###
